In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Read the dataframe

In [2]:
df = pd.read_csv('gender.csv', index_col=0)
df.rename(columns={'Unnamed: 1': 'Class'}, inplace=True)
df

,Class,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
1,male,-0.066420,0.151611,0.027740,0.052771,-0.066105,-0.041232,-0.002637,-0.158467,0.130467,...,0.025989,-0.001087,0.027260,-0.046754,-0.118619,-0.163774,-0.000590,-0.076400,0.107497,0.001567
2,male,-0.030614,0.049667,0.008084,-0.050324,0.007649,-0.063818,-0.019530,-0.119905,0.186553,...,0.044229,-0.023900,-0.028108,0.040618,-0.146579,-0.141244,0.016162,0.017638,0.080610,-0.015930
3,male,-0.096178,0.061127,0.035326,-0.035388,-0.090728,-0.018634,-0.024315,-0.139786,0.052211,...,0.111141,0.059436,-0.029222,0.042115,-0.222173,-0.116908,0.093428,0.017391,0.057652,0.086116
4,male,-0.103057,0.085044,0.078333,-0.035873,-0.028163,0.004924,0.007829,-0.017016,0.114907,...,0.100793,-0.002644,-0.023388,0.029497,-0.139830,-0.119243,0.005306,-0.015100,0.161575,0.062462
5,male,-0.125815,0.120046,0.023131,-0.042901,0.038215,-0.049677,-0.054258,-0.130758,0.173457,...,0.090197,0.067527,0.039926,0.047469,-0.056852,-0.076700,0.004966,0.028171,0.026041,0.084135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,female,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,0.030554,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
797,female,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,0.157421,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
798,female,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,0.165443,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
799,female,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,0.185083,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
800,female,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,0.048473,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

### Label the traget variables

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Class'] = le.fit_transform(df['Class'])
df

,Class,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
1,1,-0.066420,0.151611,0.027740,0.052771,-0.066105,-0.041232,-0.002637,-0.158467,0.130467,...,0.025989,-0.001087,0.027260,-0.046754,-0.118619,-0.163774,-0.000590,-0.076400,0.107497,0.001567
2,1,-0.030614,0.049667,0.008084,-0.050324,0.007649,-0.063818,-0.019530,-0.119905,0.186553,...,0.044229,-0.023900,-0.028108,0.040618,-0.146579,-0.141244,0.016162,0.017638,0.080610,-0.015930
3,1,-0.096178,0.061127,0.035326,-0.035388,-0.090728,-0.018634,-0.024315,-0.139786,0.052211,...,0.111141,0.059436,-0.029222,0.042115,-0.222173,-0.116908,0.093428,0.017391,0.057652,0.086116
4,1,-0.103057,0.085044,0.078333,-0.035873,-0.028163,0.004924,0.007829,-0.017016,0.114907,...,0.100793,-0.002644,-0.023388,0.029497,-0.139830,-0.119243,0.005306,-0.015100,0.161575,0.062462
5,1,-0.125815,0.120046,0.023131,-0.042901,0.038215,-0.049677,-0.054258,-0.130758,0.173457,...,0.090197,0.067527,0.039926,0.047469,-0.056852,-0.076700,0.004966,0.028171,0.026041,0.084135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,0,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,0.030554,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
797,0,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,0.157421,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
798,0,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,0.165443,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
799,0,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,0.185083,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
800,0,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,0.048473,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

### Divide the features and target variables

In [4]:
X = df.drop('Class', axis = 1)
y = df['Class']

### Define the final required dimension count

In [5]:
# Define the number of dimensions (d) and the desired reduced dimensionality (d')
d = X.shape[1]  # 128 dimensions
d_prime = 2  # You can change this value based on your requirements

### Seperate the data into train and test samples

In [6]:
male_sample = X[0:10]
female_sample = X[400:410]
X_test = pd.concat([male_sample, female_sample], axis = 0)
male_sample = y[0:10]
female_sample = y[400:410]
y_test = pd.concat([male_sample, female_sample], axis = 0)

In [7]:
X_train = X.drop(X_test.index, axis = 0).reset_index(drop = True)
y_train = y.drop(y_test.index, axis = 0).reset_index(drop = True)

### Compute Mean Vectors for each class

In [8]:
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
mean_male = np.mean(X_train[y_train == 0, :], axis=0)
mean_female = np.mean(X_train[y_train == 1, :], axis=0)

### Within Class Scatter Matrix

In [13]:
# Initialize the within-class scatter matrix S_W
S_W = np.zeros((d, d))  # d is the number of features (128 in your case)

# Calculate the scatter matrix for the male class
scatter_male = np.zeros((d, d))
for x in X_train[y_train == 1, :]:
    x_minus_mean = x - mean_male
    scatter_male += np.outer(x_minus_mean, x_minus_mean)

# Calculate the scatter matrix for the female class
scatter_female = np.zeros((d, d))
for x in X_train[y_train == 0, :]:
    x_minus_mean = x - mean_female
    scatter_female += np.outer(x_minus_mean, x_minus_mean)

# Sum the scatter matrices for each class to get S_W
S_W = scatter_male + scatter_female

In [14]:
S_W

array([[ 2.73005947, -0.03219359, -0.76630889, ...,  0.42816232,
         0.1585185 ,  0.18321804],
       [-0.03219359,  2.09271053, -0.34614651, ..., -0.24198452,
         0.03511052,  0.10677883],
       [-0.76630889, -0.34614651,  2.8791891 , ..., -0.37163804,
        -0.51187172, -0.2983453 ],
       ...,
       [ 0.42816232, -0.24198452, -0.37163804, ...,  1.85646909,
         0.06735701,  0.16435001],
       [ 0.1585185 ,  0.03511052, -0.51187172, ...,  0.06735701,
         2.05555291,  0.14707403],
       [ 0.18321804,  0.10677883, -0.2983453 , ...,  0.16435001,
         0.14707403,  1.87352342]])

### Between Class Scatter Matrix

In [15]:
# Calculate the overall mean vector for the entire dataset
mean_overall = np.mean(X_train, axis=0)

# Initialize the between-class scatter matrix S_B
S_B = np.zeros((d, d))

# Calculate the scatter matrix for the male class
scatter_male1 = np.zeros((d, d))
count_male = len(X_train[y_train == 1])
mean_minus_overall_male = mean_male - mean_overall
scatter_male1 = count_male * np.outer(mean_minus_overall_male, mean_minus_overall_male)

# Calculate the scatter matrix for the female class
scatter_female1 = np.zeros((d, d))
count_female = len(X_train[y_train == 0])
mean_minus_overall_female = mean_female - mean_overall
scatter_female1 = count_female * np.outer(mean_minus_overall_female, mean_minus_overall_female)

# Sum the weighted scatter matrices for each class to get S_B
S_B = scatter_male1 + scatter_female1

In [16]:
S_B

array([[ 0.13651839,  0.08500057, -0.1980772 , ...,  0.03173951,
         0.08262903,  0.07119251],
       [ 0.08500057,  0.05292399, -0.12332899, ...,  0.019762  ,
         0.05144739,  0.04432666],
       [-0.1980772 , -0.12332899,  0.28739408, ..., -0.04605148,
        -0.11988808, -0.10329461],
       ...,
       [ 0.03173951,  0.019762  , -0.04605148, ...,  0.0073792 ,
         0.01921064,  0.01655173],
       [ 0.08262903,  0.05144739, -0.11988808, ...,  0.01921064,
         0.05001199,  0.04308994],
       [ 0.07119251,  0.04432666, -0.10329461, ...,  0.01655173,
         0.04308994,  0.03712594]])

### Eigen Values and Eigen Vectors

In [17]:
# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(
    np.linalg.inv(scatter_male + scatter_female).dot(S_B)
)

# Sort the eigenvalues and eigenvectors
eigen_pairs = [(eigenvalues[i], eigenvectors[:, i]) for i in range(len(eigenvalues))]
eigen_pairs = sorted(eigen_pairs, key=lambda x: x[0], reverse=True)

# Choose the top d' eigenvectors and create the transformation matrix W
W = np.array([eigen_pair[1] for eigen_pair in eigen_pairs[:d_prime]]).T

### Get the final dataframe with d' dimensions

In [18]:
# Project the data onto the reduced-dimensional space
X_train_lda = X_train.dot(W)
X_test_lda = X_test.dot(W)

In [19]:
X_train_lda

array([[1.85462852e-06-1.06660530e-06j, 1.85462852e-06+1.06660530e-06j],
       [3.18544817e-06-9.06803402e-06j, 3.18544817e-06+9.06803402e-06j],
       [4.50567122e-06-1.67986047e-05j, 4.50567122e-06+1.67986047e-05j],
       ...,
       [5.94273997e-07+2.22363204e-07j, 5.94273997e-07-2.22363204e-07j],
       [2.39938318e-06-1.33731251e-05j, 2.39938318e-06+1.33731251e-05j],
       [1.38441098e-06-6.62244238e-06j, 1.38441098e-06+6.62244238e-06j]])

In [20]:
X_test_lda = X_test_lda.to_numpy()

### We will be using KNN Classifier for modelling

#### Euclidean Distance Function

In [21]:
def euclidean(X_train, X_test):
    all_point_distances = []
    for i in X_test:
        point_distance = []
        for j in X_train:
            dist = np.sqrt(np.sum((j-i)**2))
            point_distance.append(dist)
        all_point_distances.append(point_distance)
    arr = np.array(all_point_distances)
    return arr

#### KNN Model Function

In [22]:
def knn_classify(distance_array, y_train, k):
    array_indexes = []
    for point in distance_array:
        nearest_points = np.argsort(point)[:k]
        array_indexes.append(nearest_points)
    array_indexes = np.array(array_indexes)
    
    y_values = []
    for point in array_indexes:
        values = []
        for i in point:
            values.append(y_train[i])
        y_values.append(values)
    y_pred = []
    for point in y_values:
        y_pred.append(max(point, key = point.count))
    y_pred = np.array(y_pred)
    return y_pred

#### Accuracy Function

In [23]:
def check_accuracy(y_pred, y_test):
    return np.sum(y_pred == y_test) / len(y_test)

In [24]:
y_test = y_test.to_numpy()

### Final Evaluation

In [28]:
eud = euclidean(X_train_lda, X_test_lda)
k = 3
y_pred = knn_classify(eud, y_train, k)
print(f"Actual Output: {y_test}\nPredicted Output: {y_pred}")

Actual Output: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
Predicted Output: [1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0]

In [29]:
print(f"Accuracy with k={k} : {check_accuracy(y_pred, y_test)*100}%")

Accuracy with k=3 : 90.0%